# Generated by Django 4.1.7 on 2023-03-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name=' название группы')),
                ('description', models.CharField(max_length=500, verbose_name='описание группы')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='имя участника')),
                ('wish', models.CharField(max_length=500, verbose_name='пожелание')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='groups.group', verbose_name='группа')),
                ('recipient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='подопечный')),
            ],
        ),
    ]
