# Generated by Django 4.1.7 on 2023-03-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.participant', verbose_name='подопечный'),
        ),
    ]
