# Generated by Django 4.1.7 on 2023-03-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_participant_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.participant', verbose_name='подопечный'),
        ),
    ]
